pathfinder/urls.py
from django.contrib import admin
from django.urls import path
from core import views as core_views
from core import api_views

urlpatterns = [
    path('', core_views.index_view),
    path('admin/', admin.site.urls),
    path('api/pathfinder/', api_views.ElevationMapView.as_view()),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms

class PathfinderForm(forms.Form):
    elevation_file = forms.FileField()
    show_path = forms.BooleanField(required=False)

core/views.py
from django.shortcuts import render
from core.forms import PathfinderForm
from core.pathfinder import ElevationMap, PathFinder, MapImage
from io import BytesIO
import base64
# Create your views here.


def index_view(request):
    form = PathfinderForm()
    image_data_url = None

    if request.method == "POST":
        form = PathfinderForm(request.POST, request.FILES)
        if form.is_valid():
            elevation_file = request.FILES['elevation_file']
            data = elevation_file.read().decode('utf-8').strip().split("\n")
            map = ElevationMap(data=data)
            pathfinder = PathFinder(map)
            map_image = MapImage(map, pathfinder)
            map_image.pathfinder.find_optimal_path()
            print(map_image.canvas)

            output = BytesIO()
            map_image.draw_image()
            map_image.draw_path()
            map_image.canvas.save(output, format='PNG')

            image_data = output.getvalue()
            image_data_url = 'data:image/png;base64,' + base64.b64encode(
                image_data).decode("utf-8")

    return render(request, "core/index.html", {
        "form": form,
        "image_url": image_data_url
    })

core/templates/core/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Pathfinder</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    
</head>

<body>
    <main>
        <h1>Pathfinder</h1>
        <a href="{% static "sample-data/rocky-mountain-south.asc" %}" download> Test Data</a>
        
        <form action="" method="POST" enctype="multipart/form-data" id="js-pathfinder-form">
            {% csrf_token %}
            {{ form.as_p }}
        
            <button type="submit">Generate map</button>
        </form>
        <div id="js-map"></div>

    </main>

    <script>
        // when the submit button is clicked
        document.querySelector("#js-pathfinder-form").addEventListener('submit', function (event) {
            event.preventDefault()
            generateMapIamge()
        })

        function generateMapIamge() {
            // get the file from the file upload input
            const map = document.querySelector("#js-map")
            map.innerHTML = '<div class="lds-ripple"><div></div><div></div></div>'
            // map.innerHTML = '<img src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/0.16.1/images/loader-large.gif">'

            const fileInput = document.querySelector("#id_elevation_file")
            const file = fileInput.files[0]

            // read that file as text
            const reader = new FileReader()
            reader.addEventListener('load', function (event) {
                console.log('ok')
                const elevationData = event.target.result
                callApiWithElevationData(elevationData).then(function (responseData) {
                    const dataURL = responseData.data_url
                    map.innerHTML = `<img id="animate" style="max-width: 70em; min-width: 40em" src="${dataURL}">`
                })
            })
            reader.readAsText(file)
        }

        function callApiWithElevationData(elevationData) {
            console.log(elevationData)
            return fetch('/api/pathfinder/', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    "elevation_data": elevationData, 
                    "show_path": document.querySelector("#id_show_path").checked
                })
            }).then(response => response.json())
        }
        // send an AJAX request to /api/pathfinder with that text
        // when we get the response, add an image to the page with src of the data_url
        // that we get back
    </script>
    
</body>
</html>